//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engagement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Engagement()
        {
            this.EngagementApplications = new HashSet<EngagementApplication>();
            this.Operators = new HashSet<Operator>();
            this.OperatorEngagements = new HashSet<OperatorEngagement>();
            this.OperatorEngagementApplicationRoles = new HashSet<OperatorEngagementApplicationRole>();
            this.OperatorEngagementRoles = new HashSet<OperatorEngagementRole>();
            this.PasswordPolicies = new HashSet<PasswordPolicy>();
            this.SamlIdpConfigs = new HashSet<SamlIdpConfig>();
        }
    
        public int EngagementId { get; set; }
        public string EngagementSettings { get; set; }
        public Nullable<int> SamlIdpConfigId { get; set; }
        public bool Active { get; set; }
        public string EngagementName { get; set; }
        public string CustomerId { get; set; }
        public Nullable<int> PasswordPolicyId { get; set; }
        public string TimeZone { get; set; }
        public bool TestEngagement { get; set; }
        public System.Guid EngagementKey { get; set; }
        public string LicenseString { get; set; }
        public int SessionTimeOut { get; set; }
        public int SessionTimeoutSetting { get; set; }
        public string EngagementLogo { get; set; }
        public System.Guid EngagementGuid { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual PasswordPolicy PasswordPolicy { get; set; }
        public virtual SamlIdpConfig SamlIdpConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngagementApplication> EngagementApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operator> Operators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorEngagement> OperatorEngagements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorEngagementApplicationRole> OperatorEngagementApplicationRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorEngagementRole> OperatorEngagementRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PasswordPolicy> PasswordPolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SamlIdpConfig> SamlIdpConfigs { get; set; }
    }
}
