//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Identity : DbContext
    {
        public Identity()
            : base("name=Identity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationAccess> ApplicationAccesses { get; set; }
        public virtual DbSet<Edition> Editions { get; set; }
        public virtual DbSet<EditionFeature> EditionFeatures { get; set; }
        public virtual DbSet<Engagement> Engagements { get; set; }
        public virtual DbSet<EngagementApplication> EngagementApplications { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<OperatorCredential> OperatorCredentials { get; set; }
        public virtual DbSet<OperatorEngagement> OperatorEngagements { get; set; }
        public virtual DbSet<OperatorEngagementApplicationRole> OperatorEngagementApplicationRoles { get; set; }
        public virtual DbSet<OperatorEngagementRole> OperatorEngagementRoles { get; set; }
        public virtual DbSet<PasswordPolicy> PasswordPolicies { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SamlIdpConfig> SamlIdpConfigs { get; set; }
        public virtual DbSet<SamlSpConfig> SamlSpConfigs { get; set; }

        public new IDbSet<T> Set<T>() where T : class
        {
            return base.Set<T>();
        }

        public void SetModified(object entity)
        {
            Entry(entity).State = EntityState.Modified;
        }

        public void SetAdd(object entity)
        {
            Entry(entity).State = EntityState.Added;
        }
    }

   
}
