//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operator()
        {
            this.OperatorCredentials = new HashSet<OperatorCredential>();
            this.OperatorEngagements = new HashSet<OperatorEngagement>();
            this.OperatorEngagementApplicationRoles = new HashSet<OperatorEngagementApplicationRole>();
            this.OperatorEngagementRoles = new HashSet<OperatorEngagementRole>();
            this.PasswordPolicies = new HashSet<PasswordPolicy>();
            this.SamlIdpConfigs = new HashSet<SamlIdpConfig>();
        }
    
        public int OperatorId { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string EmployeeNumber { get; set; }
        public string Info { get; set; }
        public string Culture { get; set; }
        public string Language { get; set; }
        public bool Superuser { get; set; }
        public bool GlobalVisible { get; set; }
        public Nullable<int> SamlIdpConfigId { get; set; }
        public Nullable<int> MasterEngagementId { get; set; }
        public int Status { get; set; }
        public string TimeZone { get; set; }
        public Nullable<int> PasswordPolicyId { get; set; }
        public int FailedLoginCount { get; set; }
        public Nullable<System.DateTime> LastFailedLoginTimestamp { get; set; }
        public Nullable<System.DateTime> ActivationEmailSent { get; set; }
        public Nullable<System.DateTime> BalancerLastLoginTimestamp { get; set; }
        public Nullable<System.DateTime> TaskManagerLastLoginTimestamp { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid MasterEngagementGuid { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual Engagement Engagement { get; set; }
        public virtual PasswordPolicy PasswordPolicy { get; set; }
        public virtual SamlIdpConfig SamlIdpConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorCredential> OperatorCredentials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorEngagement> OperatorEngagements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorEngagementApplicationRole> OperatorEngagementApplicationRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorEngagementRole> OperatorEngagementRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PasswordPolicy> PasswordPolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SamlIdpConfig> SamlIdpConfigs { get; set; }
    }
}
