//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatorEngagement
    {
        public int OperatorId { get; set; }
        public int EngagementId { get; set; }
        public System.Guid OperatorEngagementGuid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid EngagementGuid { get; set; }
    
        public virtual Engagement Engagement { get; set; }
        public virtual Operator Operator { get; set; }
    }
}
