//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamlIdpConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SamlIdpConfig()
        {
            this.Engagements = new HashSet<Engagement>();
            this.Operators = new HashSet<Operator>();
        }
    
        public int SamlIdpConfigId { get; set; }
        public string AssertionConsumerServiceUrl { get; set; }
        public bool SignAuthnRequest { get; set; }
        public bool WantSamlResponseSigned { get; set; }
        public bool WantAssertionSigned { get; set; }
        public bool WantAssertionEncrypted { get; set; }
        public bool UseEmbeddedCertificate { get; set; }
        public bool SignLogoutRequest { get; set; }
        public string SingleSignOnServiceUrl { get; set; }
        public string SingleLogoutServiceUrl { get; set; }
        public Nullable<System.TimeSpan> ClockSkew { get; set; }
        public string SamlIdpName { get; set; }
        public string Description { get; set; }
        public Nullable<int> EngagementId { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public byte[] Certificate { get; set; }
        public string WantDigestAlgorithm { get; set; }
        public string WantSignatureAlgorithm { get; set; }
        public Nullable<System.Guid> EngagementGuid { get; set; }
        public Nullable<System.Guid> OperatorGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Engagement> Engagements { get; set; }
        public virtual Engagement Engagement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operator> Operators { get; set; }
        public virtual Operator Operator { get; set; }
    }
}
