//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamlSpConfig
    {
        public int ApplicationId { get; set; }
        public string Name { get; set; }
        public bool WantAuthnRequestSigned { get; set; }
        public bool SignSamlResponse { get; set; }
        public bool SignAssertion { get; set; }
        public bool EncryptAssertion { get; set; }
        public string AssertionConsumerServiceUrl { get; set; }
        public string SingleLogoutServiceUrl { get; set; }
        public string CertificateFile { get; set; }
    
        public virtual ApplicationAccess ApplicationAccess { get; set; }
    }
}
